---
title: "Things to consider when scheduling"
embed-resources: true
format: revealjs
---


## Core 100

* 2023-24: 37 sections of ~ 22 students each
* 26 Fall 1 sections; 11 Fall 2 sections
* Any MWF or TR slot can be used
    * Also need at least one evening section
* New Core 100 faculty are 
    * required to attend a summer orientation 
    * encouraged to take advantage of other PD opportunities.
* Contact Jane Zwart (Director of Core 100) with questions

## Rooms and Times (General)

* Assign a room for each in-person course
* Distribute classes across the day
* Use standard time slots (which may be changing a bit)
* Communicate with other programs to minimize conflicts
* Labs (mostly?) on Tuesday and Thursday

## Labs and Scheduling

* Restricting labs to TR has caused some challenges

    * difficult to schedule TAs, since they are all also in labs at those same times
    * challenges for athletes

* May be adding a MW morning lab slot -- deans will be asking for feedback

## Loads and Sections

* Contact your dean with questions about number of sections to schedule

    * I asked about increasing the number of sections due to 4/2 efficiency and
    projected larger enrollment, but didn't get a general response
    
* Adjuncts are restricted to $le$ 16 FLH per year (summer not included)

* Include non-teaching load (chair, CRF, etc.) in your schedule
